### ISSUE TITLE
Progress example produces extra progress symbols

### ISSUE THREAD

**Issue by renkun-ken** [kforner/rcpp_progress#2] opened 2015-10-16 00:43 UTC
I'm trying the following example in RStudio

```cpp
// [[Rcpp::depends(RcppProgress)]]
#include <progress.hpp>
// [[Rcpp::export]]
double long_computation3(int nb, bool display_progress=true) {
    double sum = 0;
    Progress p(nb*nb, display_progress);
    for (int i = 0; i < nb; ++i) {
        if (Progress::check_abort() )
            return -1.0;
        for (int j = 0; j < nb; ++j) {
            p.increment(); // update progress
	    sum += R::dlnorm(i+j, 0.0, 1.0, 0);
	}
    }
    return sum + nb;
}
```

```
> Rcpp::sourceCpp('rcpp_progress.cpp')
> system.time(s  <- long_computation3(3000))
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
|
   user  system elapsed 
   0.96    0.00    0.97 
> system.time(s  <- long_computation3(1000))
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
|
   user  system elapsed 
   0.13    0.00    0.11 
> system.time(s  <- long_computation3(10000))
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
********|
   user  system elapsed 
  10.75    0.00   10.79 
> system.time(s  <- long_computation3(10000))
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
********|
   user  system elapsed 
  10.89    0.00   10.93 
```

For long time computation, extra `*` are always produced.

**Comment by kforner** [comment] 2015-10-16 08:50
I cannot reproduce it, either in the regular R console nor in Rstudio. Which versions of R , OS, RcppProgress ? 
Could you reproduce it using rocker ?

**Comment by cdiener** [comment] 2016-01-13 18:48
I'm seeing a similar bug. The cpp function looks like this:

```C++
#include <Rcpp.h>
#include <vector>
// [[Rcpp::depends(RcppProgress)]]
#include <progress.hpp>

using namespace Rcpp;

// [[Rcpp::export]]
NumericVector mean_reduce(NumericMatrix m, std::vector<int> idx) {
    NumericVector res(m.ncol(), 0.0);
    
    for(int i=0; i<idx.size(); ++i) res += m(idx[i], _);
    
    return res/idx.size();
}

// [[Rcpp::export]]
NumericVector matrix_reduce(NumericMatrix m, IntegerVector idx, IntegerVector factors) {
    int nf = max(factors)+1;
    std::vector< std::vector<int> > map(nf);
    
    //Rcout<<"Building factor map..."<<std::endl;
    int fi;
    for(int i=0; i<factors.size(); ++i) {
        fi = factors[i];
        map[fi].push_back(idx[i]-1);
    }
    
    //Rcout<<"Reducing matrix..."<<std::endl;
    Progress p(nf, true);
    NumericMatrix res(nf, m.ncol());
    for(int fi=0; fi<nf; ++fi) {
        p.increment();
        res(fi, _) = mean_reduce(m, map[fi]);
    }
    
    return res;
}
```

Calling it produces:
```bash
0% 10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
|
```
(initial "|" in the wrong place)

```R
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] glmnet_2.0-2        Matrix_1.2-3        ggplot2_2.0.0      
 [4] data.table_1.9.6    stringr_1.0.0       oligo_1.34.2       
 [7] Biostrings_2.38.3   XVector_0.10.0      IRanges_2.4.6      
[10] S4Vectors_0.8.7     Biobase_2.30.0      oligoClasses_1.32.0
[13] BiocGenerics_0.16.1 doParallel_1.0.10   iterators_1.0.8    
[16] foreach_1.4.3      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3                compiler_3.2.3            
 [3] BiocInstaller_1.20.1       GenomeInfoDb_1.6.1        
 [5] plyr_1.8.3                 tools_3.2.3               
 [7] zlibbioc_1.16.0            bit_1.1-12                
 [9] RSQLite_1.0.0              preprocessCore_1.32.0     
[11] gtable_0.1.2               lattice_0.20-33           
[13] ff_2.2-13                  DBI_0.3.1                 
[15] affxparser_1.42.0          grid_3.2.3                
[17] magrittr_1.5               scales_0.3.0              
[19] codetools_0.2-14           RcppProgress_0.2.1        
[21] splines_3.2.3              GenomicRanges_1.22.3      
[23] SummarizedExperiment_1.0.2 colorspace_1.2-6          
[25] stringi_1.0-1              munsell_0.4.2             
[27] chron_2.3-47               affyio_1.40.0
```
Gcc is 4.9 and Terminal Emu is urxvt.

**Comment by kforner** [comment] 2016-01-14 12:22
Could you show me how to call your functions ?
Could you also try with an official docker image (that contain rstudio), cf https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image for instance.

**Comment by cdiener** [comment] 2016-01-14 15:26
Hi,

the bug is independent of Rstudio. Sorry for not stating that clearly. Here is the [cpp file](https://gist.github.com/cdiener/b8ecd7369c1927066b31). A simple example would be:

```R
Rcpp::sourceCpp("matrix_reduce.cpp")
m <- matrix(runif(1000), ncol=10)
idx <- sample(1:100, 1000, replace=T)
facs <- sample(0:10, 1000, replace=T
res <- matrix_reduce(m, idx, facs)
```

Which produces two terminating "|":
```bash
0% 10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
|
```

Using the rocker r-base and running

```bash
docker run -it --rm rocker/r-base
```
followed by

```R
install.packages(c("Rcpp", "RcppProgress"))
download.file("https://gist.githubusercontent.com/cdiener/b8ecd7369c1927066b31/raw/adef2bf9c36664a616960b92ceb7b55645c0bcd4/matrix_reduce.cpp", destfile="matrix_reduce.cpp")

Rcpp::sourceCpp("matrix_reduce.cpp")
m <- matrix(runif(1000), ncol=10)
idx <- sample(1:100, 1000, replace=T)
facs <- sample(0:10, 1000, replace=T
res <- matrix_reduce(m, idx, facs)
```

gives the same duplicated "|".

**Comment by kforner** [comment] 2016-01-14 19:00
@cdiener: should be fixed now, could you please confirm it ?
@renkun-ken: you did not reply, so I'll will close your issue.

**Comment by cdiener** [comment] 2016-01-14 20:15
Yes, I can confirm that the issue is fixed now with the Github version. Thanks!

**Closed** 2016-01-14 23:08 UTC
