### ISSUE TITLE
R function to clear out current progress bar instances

### ISSUE THREAD

**Issue by noamross** [kforner/rcpp_progress#4] opened 2017-01-24 22:33 UTC
Sometimes I have to kill a function which includes an RcppProgress bar, and then when I run it again, I get

    ERROR: there is already an InterruptableProgressMonitor instance defined

It would be nice for there to be a convenience R function such as `RcppProgress::clear_pbs()` that would remove any InterruptableProgressBarMonitor (or similar objects) associated with the current session, so one could continue without restarting.

**Comment by kforner** [comment] 2017-01-26 14:06
Could you provide a reproducible example ? I do not remember encountering such case.

**Comment by JohannesFriedrich** [comment] 2017-02-07 08:28
I have the same Problems as @noamross. I'm searching for a reproducible example, which is not to complicated. For the code presented [here](http://gallery.rcpp.org/articles/using-rcppprogress/) (long_computation3) it works fine. 
The error message comes from the progress.hpp  file.

**Comment by kforner** [comment] 2017-02-07 16:37
ok. Contact me as soon as you get such an example.

**Comment by artemklevtsov** [comment] 2017-04-07 14:25
Confirm this on the current version.

**Comment by kforner** [comment] 2017-04-07 14:35
@artemklevtsov so could you please contribute a reproducible example ?

**Comment by artemklevtsov** [comment] 2017-04-07 14:55
Now you can use `benchr` package with a long computation expression. Then you should abort a process and retry again in the same R session.

**Comment by kforner** [comment] 2017-11-14 12:03
I've added  the `Progress::cleanup()` method, cf 03035ca1f96e0ff30546fa615d0bdeecda6d8bbb.
Please note that is not the way open source is supposed to work. 
Users should try to alleviate as possible the work of the developer working for free for them.
A reproducible AUTOMATIC example is the minimum. For example I have no clue if this cleanup method will solve your problem.

**Comment by kforner** [comment] 2017-11-14 12:05
I'm closing the issue. Reopen it in case of problems.

**Comment by BigTimeStats** [comment] 2018-07-26 14:12
Having the same issue.

Example:

```
library(recosystem)

ratings_train <- data.frame(user = 1:100, item = sample(1:10, 100, replace = TRUE), rating = sample(1:5, 100, replace = TRUE))

r = Reco()

# While running click 'ESC'
opts <- r$tune(data_memory(ratings_train$user, ratings_train$item, ratings_train$rating),
               opts = list(dim      = c(10L, 20L),
                           costp_l1 = c(0),
                           costp_l2 = c(0.02),
                           costq_l1 = c(0),
                           costq_l2 = c(0.01),
                           lrate    = c(0.01),
                           niter = 200, nfold = 5, verbose = TRUE)) 

# Run it again
r = Reco()

opts <- r$tune(data_memory(ratings_train$user, ratings_train$item, ratings_train$rating),
               opts = list(dim      = c(10L, 20L),
                           costp_l1 = c(0),
                           costp_l2 = c(0.02),
                           costq_l1 = c(0),
                           costq_l2 = c(0.01),
                           lrate    = c(0.01),
                           niter = 200, nfold = 5, verbose = TRUE))

# second try/run generates following error:
# Error in r$tune(data_memory(ratings_train$user, ratings_train$item, ratings_train$rating),  : 
# ERROR: there is already an InterruptableProgressMonitor instance defined
```
How do I run `Progress::cleanup()`? Not having any luck, no package called "Progress" is downloadable nor is it a function in `RcppProgress`.

```
> RcppProgress::cleanup()
Error: 'cleanup' is not an exported object from 'namespace:RcppProgress'
> Progress::cleanup()
Error in loadNamespace(name) : there is no package called ‘Progress’
> install.packages('Progress')
Installing package into ‘C:/Users/vagnera/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘Progress’ is not available (for R version 3.4.3)
Warning in install.packages :
  Perhaps you meant ‘progress’ ?
```

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] recosystem_0.4.2

loaded via a namespace (and not attached):
[1] compiler_3.4.3     tools_3.4.3        yaml_2.1.16        Rcpp_0.12.17       RcppProgress_0.4.1
```

Thanks for your help!

**Comment by kforner** [comment] 2018-07-26 17:35
> How do I run Progress::cleanup()?

It is meant to be called from C++ code. We could also interface it to be callable from R.

**Comment by BigTimeStats** [comment] 2018-07-27 03:11
I see. 

Would this be something to notify the `recosystem` package author[s] about for them to call the method? 

Or, is there a way for a user to call the method, maybe with `.C()` in R or other way?

Thanks for the help!

**Comment by kforner** [comment] 2019-08-09 08:18
Sorry this is a vero very old friend. Is this issue still relevant ?

**Comment by muschellij2** [comment] 2019-10-08 21:45
The issue I believe in some cases is if you kill a long running cpp function and then try to run it again.  Ran into this today.

**Comment by kforner** [comment] 2019-10-08 21:54
@muschellij2 could you try to put up a reproducible example ? maybe using sleep/kill ...

**Comment by johannes-titz** [comment] 2020-01-15 16:15
I had the same problem and it seems that if the interval to check the user interruption is too large, then R will break by itself (is this new?) and the progress bar will not be cleaned up properly. So after setting up the progressbar, just check for user interrupt directly once:
```
Progress p(max, true);
checkUserInterrupt();`
```
This way, the user cannot interrupt from R earlier. The rest can be left as is.

**Comment by kforner** [comment] 2020-01-15 16:21
@johannes-titz Do you mean that what you propose is a workaround ? 
Have you a reproducible example ? 
For instance, can you check that without this `checkUserInterrupt();` call you get the error, and adding it solve it ?

**Comment by johannes-titz** [comment] 2020-01-15 16:24
Sorry, what I wrote is not quite correct. I was just testing it another way and it did not work. But if you reduce the checkUserInterrupt interval, it seems to work.

**Comment by johannes-titz** [comment] 2020-01-15 17:07
Ok, so here is an example:
The current version of fastpos on CRAN has the follwing C++ code:
```C++
Progress p(number_of_studies, true);
for (int k = 0; k < number_of_studies; k++) {
    if (k % 10000 == 0) {
      checkUserInterrupt();
    }
    p.increment();
    ret[k] = simulate_one_pos(x_pop, y_pop, index_pop, sample_size_min,
                              sample_size_max, replace, lower_limit,
                              upper_limit);
}
```

Install the package and run an example:
```R
install.packages("fastpos")
fastpos::find_critical_pos(0.5)
```
During the example press ESC. Then run it again:
```R
fastpos::find_critical_pos(0.5)
```

You will get:

Error in simulate_pos(x, y, n_studies, sample_size_min, sample_size_max,  : 
  ERROR: there is already an InterruptableProgressMonitor instance defined

Now restart R and try the development version, which I just updated to check at every iteration
(see https://github.com/johannes-titz/fastpos/commit/45a02c357b07de729e8fdccf45f14f1a2f758620 -- you can see that I tried to check at 500 iterations before, which was still not enough)

```R
devtools::install_github("johannes-titz/fastpos")
fastpos::find_critical_pos(0.5)
```

Press ESC during the function call and then call the function again:

```R
fastpos::find_critical_pos(0.5)
```
Now, the output looks a bit different and I do not get the error. 

Not sure if this is of any help to someone, but it seems to work for my package---although I do not really like the solution. Obviously you will need to figure out the appropriate checking interval for your code so that the time interval will be short. At first I tried 0.5s (about every 500 iterations), but this was still not short enough. Now I check at every iteration (what a waste of resources).

Another solution might be to somehow ignore the interruption in the R function and only allow it to work in the C++ function. Not sure if this is a real alternative and how it would play out.

Any other ideas?

I hope the example works and can be followed. If needed, I can update it.

**Comment by johannes-titz** [comment] 2020-01-16 10:12
Actually I tried your suggestion before. For a reproducible example use the pb branch (see the change here: https://github.com/johannes-titz/fastpos/commit/bc291b8f1a3b8660efe065b0f415307fab109767).

```
Progress p(number_of_studies, true);
  for (int k = 0; k < number_of_studies; k++) {
    if (k % 10000 == 0) {
      if (Progress::check_abort() ) {
        return ret;
      }
    }
    p.increment();
    ret[k] = simulate_one_pos(x_pop, y_pop, index_pop, sample_size_min,
                              sample_size_max, replace, lower_limit,
                              upper_limit);
  }
```

Run:
```
devtools::install_github("johannes-titz/fastpos@pb")
fastpos::find_critical_pos(0.5)
```

Abort during execution. Then call the function again:

```
fastpos::find_critical_pos(0.5)
``` 

Still produces the error. If I check at every iteration, your version also works.

The CheckUserInterrupt I copied from somewhere and it has actually worked for me some time ago. Is this supposed to make a big difference? At least it does not seem to be the cause of the problem.

Maybe there is still something wrong in my code. I am not really familiar with C++ but only use it to speed up crucial parts for computations in R.

The cleanup function also does not help. (p.cleanup(); before return)

By the way, no need to be rude ("weird things").

**Comment by kforner** [comment] 2020-01-16 10:23
> By the way, no need to be rude ("weird things").

This was absolutely not my intention, sorry for that. I just meant code locations that may be involved.

> Is this supposed to make a big difference?

Yes, in multi-threaded code 

> The cleanup function also does not help. (p.cleanup(); before return)

I don't understand what's going on... 
The message:
> ERROR: there is already an InterruptableProgressMonitor instance defined
means that there's an InterruptableProgressMonitor object. 
but the cleanup() function deletes it.

**Comment by johannes-titz** [comment] 2020-01-16 10:36
> > By the way, no need to be rude ("weird things").
> 
> This was absolutely not my intention, sorry for that. I just meant code locations that may be involved.

No worries! :)
> 
> > Is this supposed to make a big difference?
> 
> Yes, in multi-threaded code

Ok, makes sense.
> 
> > The cleanup function also does not help. (p.cleanup(); before return)
> 
> I don't understand what's going on...
> The message:
> 
> > ERROR: there is already an InterruptableProgressMonitor instance defined
> 
> means that there's an InterruptableProgressMonitor object.
> but the cleanup() function deletes it.

To make it explicit (with the cleanup function) see here: https://github.com/johannes-titz/fastpos/commit/10d93b58683bf3f34f695a214a3c602a0c1ca9c0

Same procedure, install the pb branch and run the function...does not make any difference.

The problem is the following: The checking interval (k % 10000) is too long. So the interruption is not registered in C++ but only in R. R seems to kill everything and so the cleanup is never executed.

I am pretty sure that this was not the normal behavior some time ago. Without a check for interruption it was not possible to interrupt a C++ call from R by pressing ESC. Now it is. Not really sure what has changed (although the problem seems to be even older judging from the first mention here in 2017). A solution would be to check for user interruption in an R function and either ignore it or clean up the progress bar there.

**Comment by kforner** [comment] 2020-01-16 10:41
> So the interruption is not registered in C++ but only in R. R seems to kill everything and so the cleanup is never executed.

Ok, makes sense. 
A possible workaround would to make the cleanup() function static (class method), and to call it prior to instantiate Progress:
```
Progress::cleanup();
Progress p(...);
```
cf https://github.com/kforner/rcpp_progress/blob/master/inst/include/progress.hpp#L50

Do you want to give it a try ?  I really don't have the time now.

**Comment by johannes-titz** [comment] 2020-01-17 08:44
I tested your suggestion and it works.

But this will potentially breaks other people's code (downstream dependencies), right ? Would it be possible to delete the progress bar in the constructor (as said, I am not really familiar with C++, so I have to ask)?

Note that it is still possible that R interrupts by itself. If this happens, there is no return value and the R console is simply empty. But if the interrupt happens to be in C++, then there is a return value and the corresponding function in R needs to be stopped. By default this seems only to be possible with an error. Overall, this will lead to two different behaviors for the same situation. Maybe this is too confusing, I can elaborate if needed.

One option is to not check for an abort in C++. If ESC is pressed in R, it will stop the execution anyway. But I have no clue whether this is really always the case. Another option is to stop the R function quietly if the interrupt happens in C++, which is a bit hacky.

But in any case, your solution avoids the error, which is most important right now.

I have to do a couple of other things first, but can later check if (with the fix) (a) your package builds without problems and (b) what happens with the downstream dependencies. I can then make a pull request.

**Comment by kforner** [comment] 2020-01-17 09:02
> I tested your suggestion and it works.

great

> But this will potentially break other people's code (downstream dependencies), right ?

Why ?

> One option is to not check for an abort in C++. If ESC is pressed in R, it will stop the execution anyway. 

Have you tested this ? Does it really work ?

> Would it be possible to delete the progress bar in the constructor (as said, I am not really familiar with C++, so I have to ask)?

Replacing the `if ( monitor_singleton() != 0) {` by a call to `cleanup()` in `Progress()` should probably work. 

> I can then make a pull request.

Sounds good !

**Comment by johannes-titz** [comment] 2020-01-18 18:23
So finally I think I understand what is happening. In pure R everything works fine without the need to change anything. I can interrupt via ctrl+c and ESC does not work. In RStudio ESC interrupts the C++ function and so the progress bar is not terminated properly. 

I believe it is better to call the cleanup function in the constructor. The other solution could break other people's code because you cannot call cleanup as a normal method anymore (p.cleanup()) since it is static (Progress::cleanup()). Does this make sense?

So I added the cleanup in the constructor. It builds locally and on travis without any errors, warnings, notes. Works as expected.

Note that there are still two behaviors in RStudio: (1) interrupt happens in C++ and the corresponding function returns a value (2) interrupt happens in R, nothing is returned. So depending on when you press ESC, different things happen and different outputs are produced. In my own code I simple use a quiet error message for case (1), which looks almost the same as when R interrupts by itself.

For an example:
```
install.packages("fastpos")
devtools::install_github("johannes-titz/rcpp_progress@cleanup") # the new commit with the fix
fastpos::find_critical_pos(0.5)
```
Abort during execution. Then call the function again:

```
fastpos::find_critical_pos(0.5)
```

You can try this at different time points. No error will be thrown in contrast to the CRAN version of RcppProgress.

I made a pull request and assume the rest is yours.

**Comment by kforner** [comment] 2020-02-07 09:03
on CRAN now as 0.4.2

**Closed by kforner** 2020-02-07 09:03 UTC
